version: '2'
services:
  nginx:
    image: nginx:1.13-alpine
    container_name: ${APP_NAME}-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - fpm
    ports:
      - 8100:80
    links:
      - fpm

  fpm:
    container_name: ${APP_NAME}-fpm
    build:
      context: .
      dockerfile: ./fpm/Dockerfile
    volumes:
      - ../:/var/www/html:delegated
      - ./fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
    env_file:
      - ../.env
    links:
      - mysql

  mysql:
    container_name: ${APP_NAME}-mysql
    image: mariadb:10.4
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${APP_NAME}
      - MYSQL_USER=${APP_NAME}
      - MYSQL_PASSWORD=${APP_NAME}
      - MYSQL_DATABASE=${APP_NAME}
    volumes:
      - ./data/mysql:/var/lib/mysql:delegated
    ports:
      - 8200:3306
