FROM angelxmoreno/php7-fpm-alpine-dev:latest
LABEL maintainer="angelxmoreno@gmail.com"

# Upgrading Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
